name: 錯誤回報
description: 執行的結果不對嗎？登入發生異常嗎？請選擇這個回報
labels:
  - bug
  - need triage
body:
  - type: markdown
    attributes:
      value: |
        感謝你回報此問題並協助課表成為政大人都喜歡的樣子🤗

        請盡量詳細的描述你遇到了什麼問題。如此一來，我們就不用玩「資訊乒乓球」，同時，我們也能更快的解決你所遇到的問題。
  - type: checkboxes
    attributes:
      label: "檢查清單"
      options:
        - label: "我可以在最新的行動政大中重現這個問題 [Google Play](https://play.google.com/store/apps/details?id=tw.edu.abc.app.nuuc001)、[App Store](https://itunes.apple.com/tw/app/xing-dong-zheng-da/id1029837090)"
          required: true
        - label: "我確定這個問題沒有被別人問過─[open](https://github.com/nccu-app/schedule_issue/issues?q=is%3Aissue+is%3Aopen)或[closed](https://github.com/nccu-app/schedule_issue/issues?q=is%3Aissue+is%3Aclosed)─因為那些地方是我可以貢獻我的發現的地方。除非他已經被close了，問題卻仍存在"
          required: true
        # - label: "我已經閱讀過FAQ了，並且那沒有解決我的問題"
          # required: true
        - label: "我已經盡力完成這份問題表單了，並且我知道如果我沒寫完整，這個問題回報可能會被忽略"
          required: true
        - label: "這份問題表單僅有一項問題。若有多個問題，請開多個issue"
          required: true
        # - label: "我已經閱讀並了解貢獻指引了"
          # required: true
  - type: textarea
    attributes:
      label: "你遇到什麼問題"
      placeholder: |
        例如：必修跟選修的課程是相同的顏色
    validations:
      required: true
  - type: textarea
    attributes:
      label: "重現此問題的步驟"
      description: |
        我們看不到你的手以及你的畫面，因此請一步一步說明你做了什麼。

        如果你的問題是偶然性才會發生的，也請嘗試回想那次發生問題時你做了什麼。
      placeholder: |
        1. 打開課表
        2. 點選在大仁樓上課的自然語言處理，課號703834001
        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: "他應該要怎麼運作才對"
      placeholder: |
        顯示在大仁樓上課的自然語言處理
  - type: textarea
    attributes:
      label: "實際上他做了什麼"
      placeholder: |
        出現了在大勇樓上課的經濟學，課號000213002
  - type: textarea
    attributes:
      label: "螢幕截圖/錄影"
      description: |
        一張圖勝千萬字。
        如果可以的話，加張螢幕截圖或是螢幕錄影很可能可以幫助我們更加理解你遇到的問題。
        雖然這裡是文字輸入框，但GitHub可以讓你直接上傳檔案。
        如果你的檔案太大了以至於你無法上傳，你可以試試看先把他們壓縮，或是如果要貼雲端連結的話也很是歡迎。但是，請**記得開查看權限**
  - type: checkboxes
    attributes:
      label: "剛剛沒有不小心把個資洩漏吧？"
      description: |
        GitHub 是公開場域，你上傳的內容不僅是我們看得到，別人也可以喔！
        不小心貼錯了？沒關係，回去剛剛那兒刪除並重新上傳即可~
      options:
        - label: "沒有"
          required: true
  - type: dropdown
    attributes:
      label: "你用什麼裝置"
      description: "即使是同一個廠牌，也常常會因為不同的系統或設定不同而得到不同的結果"
      multiple: true
      options:
        - Android
        - IOS
    validations:
      required: true
  - type: textarea
    attributes:
      label: "額外資訊"
      placeholder: |
        任何其他的可能有關資訊，例如：
        * Android版本為何？IOS版本為何？
        * 你設了VPN
        * 你家的貓把你家的網路線扯掉了
  - type: markdown
    attributes:
      value: |
        感謝你把問題回報表單寫完了！我們後續將會在這邊繼續以GitHub作為回覆的管道。
        請繼續追蹤！

        ![政大電算中心 NCCU Computer Center](https://cc.nccu.edu.tw/var/file/1/1001/img/7/logo1.png)
