name: 功能改善
description: 雖然執行的結果是對的，但似乎有更好的解方？請選擇這個回報
labels:
  - enhancement
  - need triage
body:
  - type: markdown
    attributes:
      value: |
        感謝你貢獻你的想法並協助課表成為政大人都喜歡的樣子🤗

        請盡量詳細的描述你的願景為何。如此一來，我們就不用玩「資訊乒乓球」，同時，我們也能更快的將此項目列入考慮，並可能進一步去完成他。
  - type: checkboxes
    attributes:
      label: "檢查清單"
      options:
        - label: "最新的行動政大依然沒辦法滿足我的願景 [Google Play](https://play.google.com/store/apps/details?id=tw.edu.abc.app.nuuc001)、[App Store](https://itunes.apple.com/tw/app/xing-dong-zheng-da/id1029837090)"
          required: true
        - label: "我確定這個想法還沒有被人提過─[open](https://github.com/nccu-app/schedule_issue/issues?q=is%3Aissue+is%3Aopen)或[closed](https://github.com/nccu-app/schedule_issue/issues?q=is%3Aissue+is%3Aclosed)─因為那些地方是我可以貢獻我的想法的地方。除非他已經被close了，但你的期望無法達成"
          required: true
        # - label: "我已經閱讀過FAQ了，並且那沒有解決我的問題"
          # required: true
        - label: "我已經盡力闡述我的想法了，並且我知道如果我沒寫清楚，這個想法可能會消逝"
          required: true
        - label: "這份表單只為了一個目的而建。若文思泉湧，請開多個feature request"
          required: true
        - label: "我已經閱讀並了解貢獻指引了"
          required: true
  - type: textarea
    attributes:
      label: "你想要什麼功能？是因為有什麼困擾著你嗎？"
      description: |
        請注意：如果是現有功能出問題，請勿使用此表單。請使用「錯誤回報」
      placeholder: "我家的貓咪對我不理不睬的，好像很討厭我，要怎麼辦？"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "你想要我們怎麼解決？"
      description: "請盡量明確的描述一個可行的方案。我們不會通靈、不會突然就知道你的想法是什麼"
      placeholder: "每天第一堂課前30分鐘響鈴提醒我要餵牠"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "這件事目前是有辦法可以完成的嗎？如果不行，你嘗試過什麼方法？"
      placeholder: "我曾想把貓咪送人養，但我又覺得牠好可愛，不忍心割捨這位家人"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "額外資訊"
      placeholder: |
        任何其他的可能有關資訊，例如：
        * Android版本為何？IOS版本為何？
        * 這項新功能的長相為何？
  - type: markdown
    attributes:
      value: |
        感謝你把問題回報表單寫完了！我們後續將會在這邊繼續以GitHub作為回覆的管道。
        請繼續追蹤！

        ![政大電算中心 NCCU Computer Center](https://cc.nccu.edu.tw/var/file/1/1001/img/7/logo1.png)
